<?php

/**
 * Implements hook_theme().
 */
function nc_liste_theme($existing, $type, $theme, $path) {
    return array(
        'consultationsp' => array(
            'template' => 'consultationsp',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'consultationmap' => array(
            'template' => 'consultationmap',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'formconsultation' => array(
            'template' => 'formconsultation',
            'variables' => array(
                'data' => NULL,
            )
        ),
	    'formationliste' => array(
            'template' => 'formationliste',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'formationform' => array(
            'template' => 'formationform',
            'variables' => array(
                'data' => NULL,
            )
        ),
    );
}