<?php

/**
 * Implements hook_theme().
 */
function nc_liste_theme($existing, $type, $theme, $path) {
    return array(
        'consultationsp' => array(
            'template' => 'consultationsp',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'publicationliste' => array(
            'template' => 'publicationliste',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'consultationmap' => array(
            'template' => 'consultationmap',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'formconsultation' => array(
            'template' => 'formconsultation',
            'variables' => array(
                'data' => NULL,
            )
        ),
	    'formationliste' => array(
            'template' => 'formationliste',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'formationform' => array(
            'template' => 'formationform',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'offresliste' => array(
            'template' => 'offresliste',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'offresform' => array(
            'template' => 'offresform',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'concoursliste' => array(
            'template' => 'concoursliste',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'concoursform' => array(
            'template' => 'concoursform',
            'variables' => array(
                'data' => NULL,
            )
        ),
        'articleliste' => array(
	        'template' => 'articleliste',
	        'variables' => array(
		        'data' => NULL,
	        )
        ),
        'carrefourliste' => array(
	        'template' => 'carrefourliste',
	        'variables' => array(
		        'data' => NULL,
	        )
        ),
        'securedliste' => array(
	        'template' => 'securedliste',
	        'variables' => array(
		        'data' => NULL,
	        )
        ),
    );
}